CREATE TABLE IF NOT EXISTS USER_SESSIONS  (
	USER_ID INTEGER NOT NULL,
	ID INTEGER NOT NULL,
	ACTIVE BOOLEAN NOT NULL,
	PAGE_NAME VARCHAR(50) NOT NULL,
	LAST_ACTIVITY_AT TIMESTAMP NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (USER_ID, ID)
);

CREATE INDEX IF NOT EXISTS UPDATE_USER_SESSIONS_INDEX ON USER_SESSIONS (UPDATED_AT);

CREATE TABLE IF NOT EXISTS PAGES  (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS PAGES_NAME_INDEX ON PAGES (NAME);

CREATE TABLE IF NOT EXISTS EVENTS  (
	USER_ID INTEGER NOT NULL,
	ID INTEGER NOT NULL,
	EVENT_NAME VARCHAR(50) NOT NULL,
	PAGE_ID INTEGER REFERENCES PAGES (ID) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	PRIMARY KEY (USER_ID, ID)
);

CREATE INDEX IF NOT EXISTS EVENTS_CREATED_INDEX ON EVENTS (CREATED_AT);