name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize environment
        run: poetry shell
      - name: Install dependencies
        run: poetry update
      - name: Lint
        run: poetry run flake8